### ISSUE TITLE
1.8 refined stones revert to vanilla textures

### ISSUE THREAD

**Issue by nnystyxx** [MinestrapTeam/Minestrappolation-4#109]
Having Minestrappolation 1.8-4.2.666 (and previous) insatlled somehow causes Polished Andesite, Diorite, and Granite to revert to a vanilla MC appearance despite using a texture pack. Oddly, the blocks look like they should in the toolbar and hand. This is on Forge 11.14.4.1565.

http://i.imgur.com/4p8VLXJ.png What's going on here, exactly? Is there a way to override or disable it?

**Comment by werty1124** [comment]
I don't work with the textures much but I think Delocuro edited them for M4 and it's overriding the texture packs textures for them.

**Comment by Delocuro** [comment]
Like Werty said, it's probably because we override some Vanilla textures, but I'm not sure why it's only happening for the Polished versions, seeing as we override both those and the non-polished varieties. I'll re-open it and see whats going on at some point after we update to 1.9 -- there's a fair chance it'll be fixed by the new model rendering system anyways.

**Comment by Delocuro** [comment]
Okay, actually just figured it out. The reason why it's only happening for the polished stones is because we overwrite their block states to give them randomized textures -- you'll notice their rotation is randomized whenever you place a bunch down.

To fix that, just copy the .json blockstate file for each polished block from the Minestrapp assets>minecraft>blockstates folder and paste them into your resource pack's blockstates folder (if it doesn't have one, just make one). Then open each .json file and replace the file locations for our models with the file locations for the resource pack's model.

That was kind of hard to explain in text, so let me know if you run into any issues, but otherwise I'll go ahead and close this one for now.
