### ISSUE TITLE
Community: Mod Compatibility General Discussion

### ISSUE THREAD

**Issue by MrStopwatch** [MinestrapTeam/Minestrappolation-4#39]
Mods Confirmed as Compatible:
- [x] Treecapitator

Mods that Still Need Support:
- [x] Not Enough Items
- [ ] DrCyano's Base Metals

**Comment by werty1124** [comment]
Glad to hear it works but until we get the Minestrappolation alpha out  we are not that worried about compatibility.

**Comment by werty1124** [comment]
Also this is not really an issue...

**Comment by Delocuro** [comment]
Leaving this open for now as a location for info and issues with inter-mod compatibility. If anyone has questions, concerns, or general comments about how Minestrapp functions and interacts with other mods, feel free to post them here.

**Comment by medsal15** [comment]
I tried this mod with DrCyanos base metals and I found some little problems:
1)Both bronze blocks can't be swapped for recipies. Tin, copper and steel blocks can't be used to make hammers (from base metals).
2)The ore crusher doesn't work with any base metals ore (even when registered in the ore dictionary).
3)The hammers work only with the copper, tin, iron and gold ores. Special redstone/diamond/emerald/etc. ores (deepstone, etc.) can't be hammered.
4)When a stone block is hammered, it always gives normal cobblestone.
Everything else seems to work well.

**Comment by Delocuro** [comment]
The mineral block crafting issues should be an easy fix, so I'll try to have those done before the alpha. The crusher, however, will be a harder fix. I'll make an issue for it, but getting custom GUI blocks to work with OreDictionary can take a while, so no guarantees when that one will get fixed.

The hammer issues, however, are something you should report to DrCyanos, since those are issues from his mod. If only certain types of ores work with the hammer, it'd be because he didn't add support for the other types via OreDictionary, and to fix the stone to cobblestone issue, he'd have to add direct Minestrapp support within his mod to get them to drop the correct cobble type.

**Comment by medsal15** [comment]
Ok

**Comment by medsal15** [comment]
Do you remember when I asked for basemetals compatibility? It's done! Paste this at line 17 in the config and don't use "R" or "U" if you have NEI installed. http://pastebin.com/KJF2pHDn
Tell me if I forgot something.

**Comment by werty1124** [comment]
Good job medsal

**Comment by medsal15** [comment]
You still haven't added NEI compatibility.

**Comment by werty1124** [comment]
NEI is pretty low priority until we finish most of the M4 features

**Comment by dportuesi** [comment]
NEI Capability complete with every GUI now.

**Comment by werty1124** [comment]
Closing. Base metals just needed ore dictionary support which all machines have now.
